version: '3.4'

services:
  multitenant:
    image: multitenant
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 3009:3009
      - 5005:5005
