spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: Coder_1234
    username: root
server:
  port: 8089
